#!/usr/bin/env bash
echo "==create bucket"
# Check if the first argument is provided
if [ -z "$1" ]; then
    echo "There. needs to be bucket name eg ./bucket my-bucket-name."
    exit 1
fi

BUCKET_NAME=$1

aws s3api create-bucket \
 --bucket $BUCKET_NAME \
 --query Location \
 --output text

