#!/usr/bin/env bash
echo "==delete  objects"
#exit immedeatily when a cmand returns non-zero status
set -e
# Check if the first argument is provided
if [ -z "$1" ]; then
    echo "There. needs to be bucket name eg ./bucket my-bucket-name."
    exit 1
fi

BUCKET_NAME=$1

aws s3api delete-objects \
--bucket $BUCKET_NAME 