#!/usr/bin/env bash
echo "==put objects"
#exit immedeatily when a cmand returns non-zero status
set -e
#where we will store the files
OUTPUT_DIR="/tmp/s3-bash-scripts"


#remove folder if already exists
rm -r $OUTPUT_DIR

#create a output directory
mkdir -p $OUTPUT_DIR

#generate a random number
# to determine how many files to create

NUM_FILES=$((RANDOM % 6 + 5))

for ((i=1; i<=$NUM_FILES; i++)); do
    #generate random file name
    FILENAME="$OUTPUT_DIR/file_$i.txt"

    #generate random data and write to the files
    dd if=/dev/urandom of="$FILENAME" bs=1024 count=$((RANDOM % 2024 +1 ))2>/dev/null
done

tree $OUTPUT_DIR