AWSTemplateFormatVersion: 2010-09-09
Description: A Simple S3Bucket
Resources:
  S3Bucket:
    #https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-s3-bucket.html
    
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
    # we do not need to supply a bucket name as AWS will generate a random name for us.
    